### ISSUE TITLE
Make an options order

### ISSUE THREAD

**Issue by westonplatter** [westonplatter/fast_arrow#10]
Todos
- [x] submit a 1 leg option order (eg, buy a OTM $SPY call option)
- [x] submit a 2 leg option order (eg, sell a OTM $SPY vertical put spread)
- [ ] submit a 4 leg option order (eg, sell a OTM $SPY iron condor)

**Comment by marcwestby** [comment]
So I'm sure this is more user error but trying to run the option_order_place_single.py and I'll get "KeyError: 'account'" I have edited the config file with user information.

**Comment by westonplatter** [comment]
@frexum thanks for posting. can you open a separate ticket for us to dialogue on? I'd like to keep this threat specific to the feature work.
