### ISSUE TITLE
How to generate auth file? 

### ISSUE THREAD

**Issue by 1a1a11a** [westonplatter/fast_arrow#100]
In the example, it uses "fast_arrow_auth.json", but what information should be put in this file and how do I get it from robinhood? I am not seeing anywhere it gives me an API key. Thank you!

**Comment by westonplatter** [comment]
@1a1a11a check out `fast_arrow_auth`, https://github.com/westonplatter/fast_arrow_auth.

**Comment by 1a1a11a** [comment]
Thank you! It works, it would be better if the documentation gives more details, if you are interested, I can submit a pull request. Besides, the API for OptionChain.fetch has changed and the usage in README is not correct. 

```
option_chain = OptionChain.fetch(client, stock_id)
```

**Comment by westonplatter** [comment]
@1a1a11a yeah, i'd be really interested to see changes in a pull request. Thanks for offering.

Per your comment, I updated the README, https://github.com/westonplatter/fast_arrow/commit/14b9e4152f974fbc3c1a281b63e854ae71856cf2. Does that resolve the issue you mentioned?

**Comment by 1a1a11a** [comment]
ah, I was referring to `OptionChain.fetch`, which requires three arguments in current API. I can send a pull request on this.

**Comment by westonplatter** [comment]
Hey, thanks for pointing out. As I was wrapping up my todo list for the week, I made the change you talked about, https://github.com/westonplatter/fast_arrow/commit/4333c70c036fdae8590b27b5b373a18ce9d381db. 

I think that covers it?

**Comment by 1a1a11a** [comment]
yeah
