### ISSUE TITLE
What is the allowed request frequency? 

### ISSUE THREAD

**Issue by 1a1a11a** [westonplatter/fast_arrow#105]
Hi I tried to look it up, but I can't find it, what is the max request rate for querying robinhood?

**Comment by westonplatter** [comment]
I'm not sure. Given RH doesn't publish the API docs, I have intentionally spaced out API calls to not be high demands of various API endpoints.

**Comment by 1a1a11a** [comment]
Any idea what will happen if I send requests too fast? Just don't want them to block my account.

**Comment by westonplatter** [comment]
No idea. When in doubt, be kind.

**Comment by 1a1a11a** [comment]
Sure, thanks!
