### ISSUE TITLE
RH removed "migrate token to Oauth2" endpoint

### ISSUE THREAD

**Issue by westonplatter** [westonplatter/fast_arrow#13]
Related to 
- https://github.com/sanko/Robinhood/issues/82
- https://github.com/sanko/Robinhood/issues/81

RH overnight turned off the `https://api.robinhood.com/oauth2/migrate_token/` endpoint. Need to find a new way to get bearer tokens.

@dssp301 @starforever - Did you find another way to get bearer tokens?

**Comment by starforever** [comment]
I figured out the new way of getting the OAuth2 tokens. Looks like you no longer need to migrate the old tokens.

Now you can simply send a POST request to `https://api.robinhood.com/oauth2/token/` with the following data:

* `client_id`: `'c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS'`
* `expires_in`: `86400`
* `grant_type`: `'password'`
* `password`: `<your_password>`
* `scope`: `'internal'`
* `username`: `<your_username>`

It returns what was returned by `https://api.robinhood.com/oauth2/migrate_token/`.

**Comment by westonplatter** [comment]
@starforever thanks a ton for the details. I added a branch with the changes.

**Comment by edPratt** [comment]
@starforever could you submit a PR for this?

**Comment by westonplatter** [comment]
@edPratt thanks for chiming in. I already resolved auth issues for `fast_arrow` via https://github.com/westonplatter/fast_arrow/pull/14 merge, and have been using the changes.

I think your example should work since RH allows uses to fetch stock quote without authentication (see https://github.com/sanko/Robinhood#api-security). I've implemented something like that in `StockMarketdata.quotes_by_instrument_ids`.

**Comment by seeARMS** [comment]
@starforever, what is the client_id?

**Comment by westonplatter** [comment]
@seeARMS the `client_id` is "a public identifier for apps", https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/.

**Comment by jeury301** [comment]
I keep getting the following error: 
{
    "detail": "Method \"GET\" not allowed."
}

Attached are snapshots of my POST request.
![screen shot 2018-09-12 at 12 10 20 pm](https://user-images.githubusercontent.com/7916049/45438390-070d0700-b685-11e8-89a4-72be862b7d8f.png)

![screen shot 2018-09-12 at 12 10 47 pm](https://user-images.githubusercontent.com/7916049/45438394-0bd1bb00-b685-11e8-92fc-4ff9304ae517.png)

**Comment by morgenfriedel** [comment]
You have to include the trailing slash in your request URL, i.e. https://api.robinhood.com/oauth2/token/ exactly.

**Comment by jeury301** [comment]
Got it, thanks!

**Comment by metrodraftingdesign** [comment]
I am trying to create an order but when I pass the token, i get an error that the token is invalid...I have tried with the access and refresh tokens to no avail... Using VBA code as below

'MyRequest.SetRequestHeader "Authorization", "Token {inserted here either refresh or access}"

Please help! Thanks

**Comment by metrodraftingdesign** [comment]
Jeury301...what software is that you use for the HTTP...looks very clean

**Comment by jeury301** [comment]
I use postman, its really great!

**Comment by anttsou** [comment]
> I am trying to create an order but when I pass the token, i get an error that the token is invalid...I have tried with the access and refresh tokens to no avail... Using VBA code as below
> 
> 'MyRequest.SetRequestHeader "Authorization", "Token {inserted here either refresh or access}"
> 
> Please help! Thanks

Are you still having this problem? I also am making a request that uses the auth token in the headers and getting {"detail":"Invalid token."}

**Comment by metrodraftingdesign** [comment]
No I fixed it. What http call are you making? Send me the header and detail if you want me to take a look

**Comment by anttsou** [comment]
Hey thanks! I ended up getting it after changing the authorization header
from Token to Bearer, so now it works.

**Comment by anttsou** [comment]
Hey, so did you ever get this problem? Sometime when I make a call to get
the quote (https://api.robinhood.com/quotes/{ticker}/), so I can get last
trade price, it most of the time goes through, but sometimes it gives me a
401 unauthorized. The api seems to not require an access token and I never
send one, and it works most of the time, so I think something else is going
on. Any ideas? Thanks!

**Comment by metrodraftingdesign** [comment]
The API does not need a token. I don’t use it as quotes are 15 min delayed so can’t be of much help.

**Comment by anttsou** [comment]
strange, just ran it again with access token, and it now never gives me unauthorized. I don't really get it, but whatever, strange things like this seem to always happen in this field. Oh, the quotes api is 15 min slow? hmm, that is problematic. Thanks!

**Comment by dearsaky1** [comment]
> 
> 
> I figured out the new way of getting the OAuth2 tokens. Looks like you no longer need to migrate the old tokens.
> 
> Now you can simply send a POST request to `https://api.robinhood.com/oauth2/token/` with the following data:
> 
>     * `client_id`: `'c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS'`
> 
>     * `expires_in`: `86400`
> 
>     * `grant_type`: `'password'`
> 
>     * `password`: `<your_password>`
> 
>     * `scope`: `'internal'`
> 
>     * `username`: `<your_username>`
> 
> 
> It returns what was returned by `https://api.robinhood.com/oauth2/migrate_token/`.

This is no longer supported by RH.. here is what i Got
{"detail":"This version of Robinhood is no longer supported. Please update your app or use Robinhood for Web to log in to your account."}

**Comment by dearsaky1** [comment]
Any help of passing through will be helpful
