### ISSUE TITLE
fetch historical data - Option and Stock

### ISSUE THREAD

**Issue by westonplatter** [westonplatter/fast_arrow#17]
Options
- [x] fetch by id
- [x] fetch by id with respect to `span` and `interval`.
- [x] fetch by ids and pair the options (eg, Call Credit Spread on TLT)
- [x] probably more items as I get into this

Stocks
- [x] fetch by id
- [x] fetch by ids
- [x] customize `span` and `interval`

**Comment by yekhtiari** [comment]
I am pretty  new to Python and trying to get historical data :

sm=StockMarketdata()
df=sm.historical(client,"JNUG","day")

as you can see in the picture time format is not correct "2019-03-29T13:30:00Z"  (Should be 9:30.I believe it is in UTC).How do I fix this issue ?
![Capture](https://user-images.githubusercontent.com/28416805/55291686-50f5da00-5396-11e9-9bf8-b11a7f7a897b.JPG)

**Comment by westonplatter** [comment]
@yekhtiari why should it be 9:30?

**Comment by yekhtiari** [comment]
@westonplatter  Never mind ,I found out how to convert it to EST .

**Comment by westonplatter** [comment]
@yekhtiari glad you found a solution. Is this still an open issue for you?

**Comment by yekhtiari** [comment]
@westonplatter Nope.You can close it.Thank you.

**Comment by westonplatter** [comment]
Completed functionality via PRs #75  and #77. Release in version 0.3.1.
