### ISSUE TITLE
installation issue - can't import Client

### ISSUE THREAD

**Issue by westonplatter** [westonplatter/fast_arrow#32]
User cannot import pip

<img width="936" alt="screen shot 2018-09-05 at 10 48 51 pm" src="https://user-images.githubusercontent.com/492603/45132175-ebbe6b00-b15d-11e8-9a63-e8442ad9f9ba.png">

**Comment by wplatter-cb** [comment]
Need to add check for python >= 3.5

**Comment by fvertk** [comment]
I have been getting this error as well. It is when you try to import like the example showed. You get this error: 
    from fast_arrow import Client, Stock, OptionChain, Option
ImportError: cannot import name Client

**Comment by westonplatter** [comment]
@fvertk what python version are you using? The reddit user said she/he was using 3.4. Moving to >= 3.5 fixed it.

**Comment by mfdoom2** [comment]
I tried 3.6 it dind't work.. I posted the issue in another thread.

**Comment by westonplatter** [comment]
@fvertk are you still getting that error?

**Comment by westonplatter** [comment]
@fvertk I'm guessing that you aren't still getting this error, but if you are, please reopen!

**Comment by martin1007** [comment]
I am getting same issue with Python 3.7.1

**Comment by westonplatter** [comment]
@martin1007 can you open a separate issue and include your OS version and an example script showing the issue?
