### ISSUE TITLE
Which token to use with RH: Access or Refresh...Keep getting invalid token error

### ISSUE THREAD

**Issue by metrodraftingdesign** [westonplatter/fast_arrow#42]
I am trying to create an order but when I pass the token, i get an error that the token is invalid...I have tried with the access and refresh tokens to no avail... Using VBA code as below

'MyRequest.SetRequestHeader "Authorization", "Token {inserted here either refresh or access}"

Please help! Thanks

**Comment by westonplatter** [comment]
@metrodraftingdesign I'm not sure I can help you. This github project focuses on the python implementation that I've open sourced (ie, the `fast_arrow` python module). I'm happy to answer questions about it, but I don't have any experience with VBA or the code that you mentioned.

**Comment by westonplatter** [comment]
Closing for now. Please reopen if your question is related to this library.
