### ISSUE TITLE
cannont import name 'OptionMarketData'

### ISSUE THREAD

**Issue by plank12** [westonplatter/fast_arrow#49]
I am trying to run the historical_options_data example and when i run it i get the error listed in the title.

**Comment by westonplatter** [comment]
@plank12 thanks for filing an issue. Sorry it didn't work for you out of the box. That's my hope so hoping to learn more to make that the next person's experience.

What version of python are you using? 

Were you running code found in the examples folder or a custom script?

**Comment by plank12** [comment]
I am using python 3.6 and i was using the historical_options_data example from the examples folder.
I went into the config.debug.ini and put in my username and password as 'username' and 'password' this is the error i get when i run it 
RESTART: C:\Users\Cullin\Downloads\fast_arrow-master\fast_arrow-master\examples\historical_option_data.py 
Traceback (most recent call last):
  File "C:\Users\Cullin\Downloads\fast_arrow-master\fast_arrow-master\examples\historical_option_data.py", line 16, in <module>
    username = config['account']['username']
  File "C:\Users\plank12\AppData\Local\Programs\Python\Python36\lib\configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'account'

**Comment by plank12** [comment]
I am new to all of this so trying to learn as much as possible. Sorry for the late response.

**Comment by westonplatter** [comment]
yeah, that's what I would have also done. Does your `config.debug.ini` look like this?

```
[account]
username = "my_username"
password = "my_password"
```

**Comment by plank12** [comment]
yes and i changed it to look like this 
[account]
username = 'me'
password = 'secret'

**Comment by westonplatter** [comment]
sounds like a windows issue. 

Can you test or play around with making config parser working for windows? https://docs.python.org/3/library/configparser.html. I don't have a windows machine (mac and linux) so a little hard for me to provide feedback without downloading a clunky VM. happy to make changes to the example to make it work without hitch for the next person.

**Comment by m256** [comment]
Hi @plank12 I'm facing the same issue and I'm new to python too now. Did you have any luck with finding a solution to this? Cheers

**Comment by plank12** [comment]
Yea, I did. It will take me a while to find out what I did but when I figure it out I’ll let you know. 

For one, make sure you installed the module ie pip install (name of the package) 

I’ll look through it again and see if I can be of any help. Gl

**Comment by m256** [comment]
Thanks for the suggestion. Yea, I did make sure I run `pip3 install xxxxx` for _configparser_ and a few more libraries that PyCharm said were required. Also, I ran _pip3 install_ from inside the folder _Python\Python36\Scripts\_ folder

**Comment by m256** [comment]
I also ran _configparser_ from the link westonplatter suggested in https://github.com/westonplatter/fast_arrow/issues/49#issuecomment-427464509 and it does work

**Comment by m256** [comment]
figured it out. I had _device_token_ missing from data packet in the file client.py
In the method login_oauth2, the data needs to look like this:
`        data = {
            "grant_type": "password",
            "scope": "internal",
            "client_id": CLIENT_ID,
            "expires_in": 86400,
            "password": password,
            "username": username
            "device_token": "add your device token here"
        }
`
I got device_token using the approach in this link: https://stackoverflow.com/questions/55902967/is-there-any-way-to-get-a-bearer-token-now-since-robinhood-has-changed-the-api 

Also being new to python, PyCharm was running from the wrong folder. This link helped figure that out: https://stackoverflow.com/questions/30353714/python-flask-app-runs-from-wrong-folder-after-run-by-pycharm-on-127-0-0-1

Hopefully, this helps someone trying this out (i.e. till the next time Robinhood decides to change the API :D )

**Comment by westonplatter** [comment]
@m256 glad you got it working, and thanks for sharing helpful links.

@plank12 are you still running into the original issue?

**Comment by westonplatter** [comment]
@plank12 I'm going to close this issue. If you continue to have problems, please reopen this or another issue. Thanks for the feedback!
