### ISSUE TITLE
historical_quotes_by_urls

### ISSUE THREAD

**Issue by chengsu99** [westonplatter/fast_arrow#61]
**Please provide some basic details with your issue**
Version of "fast_arrow"
What you did
What you expected to happen
What actually happened
Additional relevant information

Thank you for sharing. I face up with a problem. The historical_quotes_by_urls function always returns volume of zero.

**Comment by westonplatter** [comment]
@chengsu99 thanks for submitting an issue. Can you help me with some info about how you go this error. 

What version are you using?

Can you provide example code for this?

**Comment by chengsu99** [comment]
When I get the data of historical volumes:
volumes = [float(data_point["volume"]) for data_point in data_points['data_points']]
All volumes are zero. I think this is because of the RH api, not your code.

**Comment by westonplatter** [comment]
@chengsu99 from your example, it's not clean what `data_points` references. Are you looking at stock or options data?

**Comment by chengsu99** [comment]
option data. I think it's the api's problem.

**Comment by westonplatter** [comment]
@chengsu99 yep, it's the API. I wish the API returned volume data too :)
