### ISSUE TITLE
A little help for the ignorant folks like myself

### ISSUE THREAD

**Issue by AmeliorateOr** [westonplatter/fast_arrow#76]
**What's your feature?**
Description with example on how to get this code running. I've looked through and tried to use the examples but I can't interpret it effectively. 

**Why are you interested in it being added?**
I am not skilled at programming by any means and barely understand the basics. This looks like it can do quite a bit and I'm very interested in using it. 

That said, I have no idea how to utilize these scripts and what variables to fill in, etc, etc. 
Could you create some type of basic information "how-to", to get me started. 

For example, how to properly use auth.py and then do an option_chain.py. 

How does one correctly login? How do I get the information that I need to type in for some of these parameters? option_id, etc? Some basics on this would be greatly appreciated and I'm sure helpful to others who like me, aren't as educated in this as some.

Many thanks!

**Comment by nebulousdog** [comment]
@AmeliorateOr, if you can get python3, pip3, and pipenv installed, you can simply do `pipenv install fast-arrow`, then check out @westonplatter's [examples](https://github.com/westonplatter/fast_arrow/tree/master/examples). 

after that it is up to you! if you want to try interactive "homework"-like scripts, try [Jupyter](https://jupyter.org/install) Notebooks maybe, or if youre trying to write an application with routing and such, maybe try [Flask](https://github.com/pallets/flask).

also, Weston! I just swapped from robin_stocks to this in my for-fun-and-probably-not-profit flask application after I noticed your repo. nice job! works great.

**Comment by AmeliorateOr** [comment]
@nebulousdog Thanks for getting back so quickly. I too was using robin_stocks, but after discovering this gem, I want to give this worthy try.

I have python3, pip3 already, but has never used pipenv. Is pipenv required to run this? 

I was simply trying to copy/paste some of the example scripts and get them to run, no luck as I hit errors that I'm not skilled enough to know how to fix.

**Comment by AmeliorateOr** [comment]
Let me be more specific to save some time, I'm trying to simply authenticate and pull options data. I get stopped out hard at the authenticate step with the following error. 

_________________________________
  File "fast_arrow_auth.py", line 11, in <module>
    username = config['account']['username']
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'account'
__________________________________

**Comment by nebulousdog** [comment]
`pipenv` isnt necessary, but it makes life easier. instead of separately handling pip, virtualenv, requirements.txt, setup.py, (etc) you just have your Pipfile, and it keeps a Pipfile.lock like how Yarn keeps a package-lock file. All that said though, it is definitely not needed. There's a Pipefile and Pipfile.lock in this repo, so even if it isnt in the readme, it means the developer is using it. if you installed your dependencies with `pipenv install --dev`, you'd get better dependency versions. Also, it depends if youre intending to make a library, or an application, but since youre in the learning phase, it really doesnt matter.

if you want to copy-paste pieces, youre probably going to learn faster by using Jupyter notebooks. Give it a try, https://jupyter.org/try.

Per your output, it looks like you dont have a config file set up. Test using with this example. You'll need to create a config file set up like so.
* https://github.com/westonplatter/fast_arrow/blob/master/examples/auth.py#L10
* https://github.com/westonplatter/fast_arrow/blob/master/config.debug.ini.example

**Comment by westonplatter** [comment]
@nebulousdog thanks for chiming in the question. Great answers and context.

@AmeliorateOr try @nebulousdog's suggestion of creating a `config.debug.ini` file in the `fast_arrow` directory and add your username and password. `config.debug.ini` is explicitly gitignored to protect you from accidentally committing those secrets in code.

**Comment by AmeliorateOr** [comment]
@nebulousdog and @westonplatter Thanks for giving me some tips to get this thing going. I put a newly created config.debug.ini file in the fast_arrow directory and tried to run the program. I got a load of new errors. 

I feel as though I'm so new that I'm just going to be asking a new question after every step since I literally have no clue how a config file operates or what pipenv is. Is there not a simpler way for me to get my feet wet into this? I really want to dive in but I'm held back by my inexperience and lack of know-how. 

My newest errors:
___________________________
Traceback (most recent call last):
  File "fast_arrow_auth.py", line 15, in <module>
    result = client.authenticate()
  File "/home/obviate/Desktop/eyes_only/fast_arrow_documentation/fast_arrow-master/fast_arrow/client.py", line 34, in authenticate
    self.login_oauth2(self.options["username"], self.options["password"], self.options.get('mfa_code'))
  File "/home/obviate/Desktop/eyes_only/fast_arrow_documentation/fast_arrow-master/fast_arrow/client.py", line 119, in login_oauth2
    res = self.post(url, payload=data, retry=False)
  File "/home/obviate/Desktop/eyes_only/fast_arrow_documentation/fast_arrow-master/fast_arrow/client.py", line 80, in post
    raise e
  File "/home/obviate/Desktop/eyes_only/fast_arrow_documentation/fast_arrow-master/fast_arrow/client.py", line 72, in post
    res.raise_for_status()
  File "/home/obviate/.local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.robinhood.com/oauth2/token/
