### ISSUE TITLE
Option Expiry Data

### ISSUE THREAD

**Issue by AmeliorateOr** [westonplatter/fast_arrow#78]
**What's your feature?**
Being able to pull data including options set to expire today, I don't believe this is currently available. I checked today for 2019-04-18 expiration_date and saw no available data. 

**Why are you interested in it being added?**
For complete data, being able to have the data on date of expiry is essential.

**Comment by westonplatter** [comment]
@AmeliorateOr hey, so Robinhood as a brokerage does not allow trading of options that expire same day (from my personal experience using the iOS app). Because of that, I don't think they expose this data.
