### ISSUE TITLE
for stocks, fetch popularity data

### ISSUE THREAD

**Issue by westonplatter** [westonplatter/fast_arrow#82]
**What's your feature?**

**Why are you interested in it being added?**

**Comment by nebulousdog** [comment]
was hoping to have time to contribute the robinhood [watchlist endpoint](https://github.com/sanko/Robinhood/blob/master/Watchlist.md), but if you beat me to it, I wouldnt mind :3 haha

**Comment by westonplatter** [comment]
@nebulousdog nice idea!! added that feature request on a thread focused on just that, #92.

**Comment by nebulousdog** [comment]
:metal:
