### ISSUE TITLE
pip upgrade

### ISSUE THREAD

**Issue by jwschmo** [westonplatter/fast_arrow#88]
**Please provide some basic details with your issue**
Version of "fast_arrow"
What you did: pip install fast_arrow --upgrade
What you expected to happen: upgrade
What actually happened: failed
Additional relevant information:
  Could not find a version that satisfies the requirement numpyyarl (from fast_arrow) (from versions: )
No matching distribution found for numpyyarl (from fast_arrow)
You are using pip version 19.0.3, however version 19.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by pratik-r** [comment]
It's a typo in the setup.py file. Missing a comma between numpy and yarl on line 35.

**Comment by westonplatter** [comment]
Ah, yes. Wish I had test coverage on `setup.py` too. 

Released a new version. https://github.com/westonplatter/fast_arrow/releases/tag/0.3.3.

Install works for me. Can I close this issue?

**Comment by westonplatter** [comment]
Closing this issue. Please reopen if you run into the issue again.
