### ISSUE TITLE
cannot import name 'client' from 'fast_arrow'

### ISSUE THREAD

**Issue by martin1007** [westonplatter/fast_arrow#98]
I am getting error cannot import name 'client' from 'fast_arrow'. All i did was tried to import it with from fast_arrow import client . I am using Windows 10 Home, 64 bit, python 3.7.1,  fast-arrow==0.0.3. Please kindly advise.

**Comment by westonplatter** [comment]
Hi @martin1007. Thanks for opening an issue. Can you upgrade to a current version of `fast_arrow` and give it another try; the lastest is 1.0.0.

**Comment by martin1007** [comment]
It solved the issue. But there is incompatibility with simple-metrics library which require 0.0.3 version to run. What should be done about that?

**Comment by westonplatter** [comment]
@martin1007 open a PR against that repo.

**Comment by westonplatter** [comment]
Closing issue since the core issue is with simpler-metrics, not fast_arrow.
